### ISSUE TITLE
Make a seperate layer for database

### ISSUE THREAD

**Issue by djbarnwal** [djbarnwal/hangman#5]
Currently, all the lingo terms and hints are hardcoded. A separate database tier has to be made and linked.

**Comment by akneelanjan** [comment]
Hi @djbarnwal . I would like to contribute to this issue. Shall I go forward with a react-redux model? The database of words can be placed as a reducer, thus efficiently creating a separate tier.

**Comment by djbarnwal** [comment]
Hi @akneelanjan  That sounds great. Though the main idea for a database was to encapsulate the words and hints so that they are not exposed on the client side. Still adding redux would be a great thing. We would get much more freedom with our state and that will be very helpful for the app as it gets more complex. I would suggest you to create a new issue regarding the react-redux model and then work on it. 😄
